### ISSUE TITLE
POS Tagger having issues with unicode

### ISSUE THREAD

**Issue by SakuraSound** [SakuraSound/MADden#1]
On running cgrant_postag(text) in the database, some tweets were having issues with handling unicode. I looked at the text in the database, and clearly the data was loaded properly, but the postag function seems to lose the encoding. My hope is that there is no need to recall the codecs package to deal with this.

Test Cases to see if this works...
Run pos_tag on tweets with id numbers:
115274198347292672
115274300042379264

these are confirmed to have unicode in them...

**Comment by SakuraSound** [comment]
Here is the query that was run, and the resulting error...

-- Executing query:
select a.id, cgrant_sentiment(a.twtext), cgrant_postag(b.twtext)
from tweets a, tweets b
where a.id = b.id
and a.twtextvector @@ to_tsquery('Buccaneers')
limit 1000;
ERROR:  invalid byte sequence for encoding "UTF8": 0xe2
CONTEXT:  while creating return value
PL/Python function "cgrant_postag"

*********\* Error **********

ERROR: invalid byte sequence for encoding "UTF8": 0xe2
SQL state: 22021
Context: while creating return value
PL/Python function "cgrant_postag"

**Comment by cegme** [comment]
I added a fix for this issue. You can see the fix in the latest commit.
It is probably a hack, because I just ignore the unicode characters. 
Suggestions are welcomed for a real fix.
